

services:
  vk_go:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./requests.http:/app/requests.http
    restart: unless-stopped

  tests:
    build: .
    command: go test -v ./main_test.go
    depends_on:
      - vk_gogit config --global user.email